services:
  # Frontend service (static site)
  - type: web
    name: enhanced-health-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://enhanced-health-backend.onrender.com

  # Backend service (web service)
  - type: web
    name: enhanced-health-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000 