// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfnkmdzjifjdmemebhdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmbmttZHpqaWZqZG1lbWViaGRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDY5MzMsImV4cCI6MjA1ODEyMjkzM30.RTyyivps4USj5eGqHGGi42eBXnihRhC9F5pMx_Q3e2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);